language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
before_install:
  - echo "yes" | sudo add-apt-repository ppa:rethinkdb/ppa
  - sudo apt-get update
  - sudo apt-get install rethinkdb
before_script:
  - rethinkdb </dev/null &>/dev/null & disown
  - node test/setup.js
after_script:
  - killall rethinkdb